### ISSUE TITLE
[Key] expected string length to be >= 1, but found string length of 0

### ISSUE THREAD

**Issue by michaelmannucci** [spatie/statamic-responsive-images#166]
Hi, when I use `{{ responsive:image }}` with a dynamic field everything works fine. But if I do `{{ responsive src="/url/to/my/asset.svg" }}` it throws the following error:

`Found 1 error while validating the input provided for the GetObject operation: [Key] expected string length to be >= 1, but found string length of 0`

Any ideas?

**Comment by ncla** [comment]
Is this asset in an asset container or not? Responsive addon does not handle assets well that are not within asset containers like normal Glide tag can eg. in `/resources/` dir. Does this happen with all type of asset file formats?

Can you provide additional information such as full stack trace of the error, what is the actual src path, `php artisan statamic:support:details` and maybe the .svg file?

**Comment by michaelmannucci** [comment]
Yes, it's in an asset container.

Yes it happens with any kind of asset in any asset container.

**Stack trace:**
https://flareapp.io/share/87nlQdym#F103

**Support details:**
```
Environment
Application Name: Westminster Chapel
Laravel Version: 9.30.1
PHP VersioEnvironment
Application Name: Westminster Chapel
Laravel Version: 9.30.1
PHP Version: 8.1.2
Composer Version: 2.2.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: regex
Version: 3.3.36 Solo

Statamic Addons
spatie/statamic-responsive-images: 2.13.1
visuellverstehen/statamic-classify: 2.4.0n: 8.1.2
Composer Version: 2.2.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: regex
Version: 3.3.36 Solo

Statamic Addons
spatie/statamic-responsive-images: 2.13.1
visuellverstehen/statamic-classify: 2.4.0
```

**SVG**
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M0 128C0 92.65 28.65 64 64 64H448C483.3 64 512 92.65 512 128V384C512 419.3 483.3 448 448 448H64C28.65 448 0 419.3 0 384V128zM48 128V150.1L220.5 291.7C241.1 308.7 270.9 308.7 291.5 291.7L464 150.1V127.1C464 119.2 456.8 111.1 448 111.1H64C55.16 111.1 48 119.2 48 127.1L48 128zM48 212.2V384C48 392.8 55.16 400 64 400H448C456.8 400 464 392.8 464 384V212.2L322 328.8C283.6 360.3 228.4 360.3 189.1 328.8L48 212.2z"/></svg>`

**Comment by ncla** [comment]
What is AWS doing in your project? Is it just the storage? Might be AWS storage issue then, never used it though so I can't say for sure. You could try `svg` and/or `glide` tags and see if you can replicate this same error, maybe that narrows the issue down. Also try with local disk storage too.

**Comment by michaelmannucci** [comment]
AWS is being used by anther asset container for audio files. The SVG is being called from a local asset container.

Glide doesn't throw an error but doesn't return anything, either. There's obviously something wrong with the asset containers... but I don't know what. And like I said, if I do `{{ responsive:image }}` calling a collection field, it works fine from the same containers. It also works fine in the CP... strange.

**Comment by michaelmannucci** [comment]
Strange, too, if I go to `mysite.test/assets/site/envelope.svg` it also loads the asset fine.

**Comment by ncla** [comment]
Additionally please look at #132, this extension does not handle src parameter with asset paths well as of this moment. I would just create a hidden field with default value if you need to hardcode some asset location.

**Comment by ncla** [comment]
AFAIK you can only specify asset container in your blueprints, not possible to specify it in front-end through tag parameters.

This working in an older project might mean that the core changes to the Glide cache might have broken this.

Is there an update to this? For now I am closing this, I am assuming that this is a cms issue considering you said you are having issues with Glide tag too.

**Comment by aerni** [comment]
I just ran into this issue as well. I'm sure it's an issue with this addon, as it doesn't happen when using Glide.

I've got two asset containers, one with local public assets and one with private assets on S3.

I've got an asset field in a global that is using the local asset container. Calling the `responsive` tag with the asset field as the source is causing the exception:

```antlers
{{ responsive src="{general:main_image}" }}
```

The exception makes no sense as the `main_image` isn't on S3 but using the local asset container. The exception disappears when I delete the S3 asset container.

Here's the full stacktrace and also the excepion on Flare: https://flareapp.io/share/W7zDGobm

```log
[2023-08-28 20:17:52] local.ERROR: Found 1 error while validating the input provided for the GetObject operation:
[Key] expected string length to be >= 1, but found string length of 0 {"exception":"[object] (InvalidArgumentException(code: 0): Found 1 error while validating the input provided for the GetObject operation:
[Key] expected string length to be >= 1, but found string length of 0 at /Users/michael/Code/reallife/vendor/aws/aws-sdk-php/src/Api/Validator.php:65)
[stacktrace]
#0 /Users/michael/Code/reallife/vendor/aws/aws-sdk-php/src/Middleware.php(84): Aws\\Api\\Validator->validate('GetObject', Object(Aws\\Api\\StructureShape), Array)
#1 /Users/michael/Code/reallife/vendor/aws/aws-sdk-php/src/S3/S3Client.php(599): Aws\\Middleware::Aws\\{closure}(Object(Aws\\Command), NULL)
#2 /Users/michael/Code/reallife/vendor/aws/aws-sdk-php/src/S3/S3Client.php(622): Aws\\S3\\S3Client::Aws\\S3\\{closure}(Object(Aws\\Command), NULL)
#3 /Users/michael/Code/reallife/vendor/aws/aws-sdk-php/src/S3/S3Client.php(556): Aws\\S3\\S3Client::Aws\\S3\\{closure}(Object(Aws\\Command), NULL)
#4 /Users/michael/Code/reallife/vendor/aws/aws-sdk-php/src/S3/S3Client.php(575): Aws\\S3\\S3Client::Aws\\S3\\{closure}(Object(Aws\\Command), NULL)
#5 /Users/michael/Code/reallife/vendor/aws/aws-sdk-php/src/Middleware.php(57): Aws\\S3\\S3Client::Aws\\S3\\{closure}(Object(Aws\\Command), NULL)
#6 /Users/michael/Code/reallife/vendor/aws/aws-sdk-php/src/S3/SSECMiddleware.php(59): Aws\\Middleware::Aws\\{closure}(Object(Aws\\Command), NULL)
#7 /Users/michael/Code/reallife/vendor/aws/aws-sdk-php/src/IdempotencyTokenMiddleware.php(77): Aws\\S3\\SSECMiddleware->__invoke(Object(Aws\\Command), NULL)
#8 [internal function]: Aws\\IdempotencyTokenMiddleware->__invoke(Object(Aws\\Command))
#9 /Users/michael/Code/reallife/vendor/aws/aws-sdk-php/src/functions.php(363): call_user_func(Object(Aws\\IdempotencyTokenMiddleware), Object(Aws\\Command))
#10 /Users/michael/Code/reallife/vendor/aws/aws-sdk-php/src/S3/S3Client.php(519): Aws\\serialize(Object(Aws\\Command))
#11 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Filesystem/AwsS3V3Adapter.php(54): Aws\\S3\\S3Client->getObjectUrl('siloam-producti...', '')
#12 /Users/michael/Code/reallife/vendor/statamic/cms/src/Filesystem/FlysystemAdapter.php(101): Illuminate\\Filesystem\\AwsS3V3Adapter->url('/')
#13 /Users/michael/Code/reallife/vendor/statamic/cms/src/Assets/AssetContainer.php(119): Statamic\\Filesystem\\FlysystemAdapter->url('/')
#14 /Users/michael/Code/reallife/vendor/statamic/cms/src/Assets/AssetRepository.php(66): Statamic\\Assets\\AssetContainer->url()
#15 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(1390): Statamic\\Assets\\AssetRepository->Statamic\\Assets\\{closure}(Object(Statamic\\Assets\\AssetContainer), 1)
#16 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(1457): Illuminate\\Support\\Collection->sortBy(Object(Closure), 0, true)
#17 /Users/michael/Code/reallife/vendor/statamic/cms/src/Assets/AssetRepository.php(65): Illuminate\\Support\\Collection->sortByDesc(Object(Closure))
#18 /Users/michael/Code/reallife/vendor/statamic/cms/src/Assets/AssetRepository.php(43): Statamic\\Assets\\AssetRepository->resolveContainerFromUrl('/assets/real_li...')
#19 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Statamic\\Assets\\AssetRepository->findByUrl('/assets/real_li...')
#20 /Users/michael/Code/reallife/vendor/spatie/statamic-responsive-images/src/Responsive.php(84): Illuminate\\Support\\Facades\\Facade::__callStatic('findByUrl', Array)
#21 /Users/michael/Code/reallife/vendor/spatie/statamic-responsive-images/src/Responsive.php(49): Spatie\\ResponsiveImages\\Responsive->retrieveAsset(Object(Statamic\\Fields\\Value))
#22 /Users/michael/Code/reallife/vendor/spatie/statamic-responsive-images/src/Tags/ResponsiveTag.php(39): Spatie\\ResponsiveImages\\Responsive->__construct(Object(Statamic\\Fields\\Value), Object(Statamic\\Tags\\Parameters))
#23 /Users/michael/Code/reallife/vendor/spatie/statamic-responsive-images/src/Tags/ResponsiveTag.php(33): Spatie\\ResponsiveImages\\Tags\\ResponsiveTag->index()
#24 /Users/michael/Code/reallife/vendor/statamic/cms/src/Tags/Tags.php(138): Spatie\\ResponsiveImages\\Tags\\ResponsiveTag->wildcard('url')
#25 [internal function]: Statamic\\Tags\\Tags->__call('url', Array)
#26 /Users/michael/Code/reallife/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1565): call_user_func(Array)
#27 /Users/michael/Code/reallife/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(2232): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#28 /Users/michael/Code/reallife/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(749): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#29 /Users/michael/Code/reallife/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#30 /Users/michael/Code/reallife/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(768): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('{{#\\n\\t@name Logi...', Array)
#31 /Users/michael/Code/reallife/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/Users/michael/...', '{{#\\n\\t@name Logi...', Array)
#32 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/View/View.php(195): Statamic\\View\\Antlers\\Engine->get('/Users/michael/...', Array)
#33 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#34 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#35 /Users/michael/Code/reallife/vendor/statamic/cms/src/View/View.php(111): Illuminate\\View\\View->render()
#36 /Users/michael/Code/reallife/vendor/statamic/cms/src/View/View.php(199): Statamic\\View\\View->render()
#37 /Users/michael/Code/reallife/vendor/symfony/http-foundation/Response.php(442): Statamic\\View\\View->__toString()
#38 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Http/Response.php(72): Symfony\\Component\\HttpFoundation\\Response->setContent(Object(Statamic\\View\\View))
#39 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent(Object(Statamic\\View\\View))
#40 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Routing/Router.php(911): Illuminate\\Http\\Response->__construct(Object(Statamic\\View\\View), 200, Array)
#41 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Routing/Router.php(878): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\View\\View))
#42 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\View\\View))
#43 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/michael/Code/reallife/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/michael/Code/reallife/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/michael/Code/reallife/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\AddViewPaths->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/michael/Code/reallife/vendor/statamic/cms/src/Http/Middleware/Localize.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Users/michael/Code/reallife/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\HandleToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/michael/Code/reallife/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/michael/Code/reallife/app/Http/Middleware/RedirectIfAuthenticated.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#66 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#73 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#74 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#75 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#76 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#77 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/michael/Code/reallife/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /Users/michael/Code/reallife/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /Users/michael/Code/reallife/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /Users/michael/Code/reallife/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 /Users/michael/Code/reallife/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 /Users/michael/Code/reallife/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#89 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#90 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#91 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#92 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#94 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#95 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#96 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#97 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#98 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#99 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#100 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#101 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#102 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#103 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#104 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#105 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#106 /Users/michael/Code/reallife/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#107 /Users/michael/Code/reallife/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#108 /Users/michael/.composer/vendor/laravel/valet/server.php(110): require('/Users/michael/...')
#109 {main}
```
