### ISSUE TITLE
Errors on uploading assets

### ISSUE THREAD

**Issue by PhilippeGauthier** [spatie/statamic-responsive-images#206]
### Bug description

I'm getting this error when uploading assets in the CP:

Call to undefined method Spatie\ResponsiveImages\Breakpoint::dispatchImageJobs()

### How to reproduce

Only happens on the Laravel Forge server. Not happening on local despite the same version numbers for statamic / addons. 

### Logs

```shell
[2023-02-09 16:40:21] staging.ERROR: Call to undefined method Spatie\ResponsiveImages\Breakpoint::dispatchImageJobs() {"userId":"b9e2f7d9-9d25-4f60-acc4-4926966c3bec","exception":"[object] (Error(code: 0): Call to undefined method Spatie\\ResponsiveImages\\Breakpoint::dispatchImageJobs() at /home/forge/staging.hellyesvs.com/vendor/spatie/statamic-responsive-images/src/Listeners/GenerateResponsiveVersions.php:32)
[stacktrace]
#0 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): Spatie\\ResponsiveImages\\Listeners\\GenerateResponsiveVersions->Spatie\\ResponsiveImages\\Listeners\\{closure}()
#1 /home/forge/staging.hellyesvs.com/vendor/spatie/statamic-responsive-images/src/Listeners/GenerateResponsiveVersions.php(33): Illuminate\\Support\\Collection->each()
#2 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): Spatie\\ResponsiveImages\\Listeners\\GenerateResponsiveVersions->handle()
#3 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#4 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(451): Illuminate\\Events\\Dispatcher->dispatch()
#5 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Foundation/Events/Dispatchable.php(14): event()
#6 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Assets/Asset.php(856): Statamic\\Events\\Event::dispatch()
#7 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Controllers/CP/Assets/AssetsController.php(87): Statamic\\Assets\\Asset->upload()
#8 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Assets\\AssetsController->store()
#9 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#10 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#11 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#12 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#13 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#14 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/DeleteTemporaryFileUploads.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DeleteTemporaryFileUploads->handle()
#16 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\CountUsers->handle()
#18 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/CP/BootUtilities.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootUtilities->handle()
#20 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/CP/BootPreferences.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootPreferences->handle()
#22 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/CP/BootPermissions.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootPermissions->handle()
#24 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\Localize->handle()
#26 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\Authorize->handle()
#28 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\AddToasts->handle()
#30 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle()
#32 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle()
#34 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#36 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#38 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#40 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#42 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#43 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#45 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#47 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle()
#49 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#51 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#52 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#53 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#54 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#55 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#56 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle()
#58 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#60 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#62 /home/forge/staging.hellyesvs.com/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#64 /home/forge/staging.hellyesvs.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#66 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#68 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#69 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#71 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#72 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#74 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#76 /home/forge/staging.hellyesvs.com/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#78 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#80 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#82 /home/forge/staging.hellyesvs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#83 /home/forge/staging.hellyesvs.com/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#84 {main}
"}
```

### Environment

```yaml
Environment
Application Name: Versus
Laravel Version: 9.45.1
PHP Version: 8.1.13
Composer Version: 2.5.2
Environment: staging
Debug Mode: ENABLED
URL: staging.hellyesvs.com
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.3 PRO

Statamic Addons
aryehraber/statamic-logbook: 2.1.0
spatie/statamic-responsive-images: 3.1.0
statamic/seo-pro: 4.0.1
studio1902/statamic-peak-commands: 1.20
```

### Installation

Starter Kit using via CLI

### Antlers Parser

regex (default)

**Comment by ncla** [comment]
That method does not exist anymore on that class. Have you restarted your worker so it uses the updated packages/code?

**Comment by PhilippeGauthier** [comment]
I just rebooted the server and am still seeing the error. Is there a more specific command to restart the worker?

**Comment by ncla** [comment]
Just looked at the code, it is a bug.

**Comment by ncla** [comment]
Should be good now in v3.1.1.
