### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by pryley** [spatie/statamic-responsive-images#60]
I'm getting a "Division by zero" error with v2.5.3, looking at the logs it seems to be related to the ratio breakpoints feature (perhaps related to #41 ?).

```
[previous exception] [object] (ErrorException(code: 0): Division by zero at /home/production/domain.com/vendor/spatie/statamic-responsive-images/src/Responsive.php:72)
[stacktrace]
#0 /home/production/domain.com/vendor/spatie/statamic-responsive-images/src/Responsive.php(72): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/production/domain.com/vendor/spatie/statamic-responsive-images/src/Tags/ResponsiveTag.php(55): Spatie\\ResponsiveImages\\Responsive->breakPoints()
#2 /home/production/domain.com/vendor/spatie/statamic-responsive-images/src/Tags/ResponsiveTag.php(32): Spatie\\ResponsiveImages\\Tags\\ResponsiveTag->index()
#3 /home/production/domain.com/vendor/statamic/cms/src/Tags/Tags.php(131): Spatie\\ResponsiveImages\\Tags\\ResponsiveTag->wildcard()
#4 [internal function]: Statamic\\Tags\\Tags->__call()
```

Example tag usage:

```
{{ responsive:image
     class="absolute h-full w-full left-0 top-0 rounded object-cover object-center" 
     glide:fit="crop_focal"
     glide:width="1024" 
     ratio="5/3" md:ratio="2/3"
     width="600"
}}
```

The problem causes a "500 | Server error" on the frontend of the website, but seems to resolve itself after republishing and refreshing the page a few times.

**Comment by riasvdv** [comment]
What type of image is your asset? This line https://github.com/spatie/statamic-responsive-images/blob/master/src/Responsive.php#L72 gets the width and the height straight from the asset which should always have values.

**Comment by pryley** [comment]
The image was a PNG file. Do you think this would have anything to do with `generate_on_upload` being set to false?

```php
return [
    'breakpoint_unit' => 'px',
    'breakpoints' => [
        'sm' => 640,
        'md' => 768,
        'lg' => 1024,
        'xl' => 1280,
        '2xl' => 1440,
    ],
    'generate_on_upload' => false,
    'image_job' => \Spatie\ResponsiveImages\Jobs\GenerateGlideImageJob::class,
    'max_width' => 1280,
    'placeholder' => false,
    'queue' => 'default',
    'webp' => true,
];
```

**Comment by pryley** [comment]
I think this issue can be closed. I'm not sure what caused the original issue, but it's likely related to a specific version of Statamic as the asset should have those values set as stated above.
